// <auto-generated />
using System;
using ALEXforums.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ALEXforums.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230803192447_forums")]
    partial class forums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Testforum")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ALEXforums.Data.Entity.Message", b =>
                {
                    b.Property<Guid>("ThemeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtMessage")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ThemeId", "UserId");

                    b.ToTable("Messages", "Testforum");
                });

            modelBuilder.Entity("ALEXforums.Data.Entity.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentTheme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtTheme")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrlTheme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleTheme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Themes", "Testforum");
                });

            modelBuilder.Entity("ALEXforums.Data.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisteredDt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users", "Testforum");
                });
#pragma warning restore 612, 618
        }
    }
}
